spring.application.name=demo
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.hikari.jdbc-url=





# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/polymarket
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update